databases:
  - name: smartjudi
    databaseName: smartjudi
    user: jood

services:
  - type: web
    name: smartjudi
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd smartju && gunicorn smartju.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: smartju.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: smartjudi
          property: connectionString
      - key: ALLOWED_HOSTS
        value: smartjudi.onrender.com
